### ISSUE TITLE
No results when building a "website" style VB.NET project as opposed to a "Web Application" type project

### ISSUE THREAD

**Issue by hoodoer** [security-code-scan/security-code-scan#104]
I'm building a VB.NET "website" project, and it seems many static analysis tools don't work on this type of visual studio project. SonarQube definitely doesn't work (and is documented as such). 

I noticed I'm also not getting any issues from SCS when building the project either, and I'm curious if this is due to the project type. 

![image](https://user-images.githubusercontent.com/34483186/52236892-1b50db00-2896-11e9-9ab6-cccda321c864.png)

**Comment by JarLob** [comment]
99% of C# tests have VB.NET counterpart.

- Did you check Error List window instead of Output? See https://security-code-scan.github.io/#TestingonWebGoat.NET
- Did you enable Full Solution Analysis? Otherwise you get warning only from **open** documents.
- Do you have a line of code that should trigger a warning like `System.Security.Cryptography.MD5.Create()`?
- Can you attach a sample project?
