### ISSUE TITLE
Regarding sanitizer

### ISSUE THREAD

**Issue by projectrvce** [security-code-scan/security-code-scan#121]
Hai, 
    I wanted to know how the sanitizers work. If the variable is tainted and is passed to any of the sanitizers listed in main.yml file does it make the variable untainted or it is still tainted ?

**Comment by JarLob** [comment]
It doesn't make it untainted, but applies the sanitizer's flag from https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml#L52 I.e. the input is still tainted, but htmlescaped for example, no warning is shown for Sinks that require htmlescaped input.

**Comment by JarLob** [comment]
Said that, there is a special Taint - Safe that basically marks the value as sanitized against all possible threats. https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml#L309

**Comment by projectrvce** [comment]
hai,   Can you tell me which part of the code is setting the flag and making the analyser silent?

**Comment by JarLob** [comment]
Tell what you are trying to achieve and maybe I can help you.

**Comment by projectrvce** [comment]
consider there is some tainted input variable, query.
string q1 = Encoder.HtmlEncode(query) //sanitizing
SqlCommand cmd  = new SqlCommand(q1); // Doesn't raise diagnostic and it is fine
SqlDataAdapter adapter = new SqlDataAdapter(cmd);  // still raises the diagnostic.. 
Can you please help me in resolving the SqlDataAdapter one ?

**Comment by JarLob** [comment]
1. I tried to compile and it gives me the warning in both cases.
2. Even if it didn't `HtmlEncode` doesn't protect you from SQL injection. You could register your own taint sanitizer function as I said before, but then you need to override `SqlCommand` and `SqlDataAdapter` sinks (because filtering single quotes or doing any kind of sanitization is not the recommended way to mitigate SQLi - you should use parameterized queries instead). Take a look at [`HttpResponse.Write`](https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml#L767) how it defines that `HtmlEscaped` input is safe and no warning has to be shown.

**Comment by projectrvce** [comment]
Yeah yeah I got it now. So you mean even if  the input is HtmlEscaped it should raise diagnostic as it doesn't mitigate SQLi.
