### ISSUE TITLE
External configuration file. Exception during deserialization

### ISSUE THREAD

**Issue by CodeGlitcher** [security-code-scan/security-code-scan#138]
Hello,

I tried to use an extranal configuration file to enable audit mode. 
When i place this file:
https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml

in %LocalAppData%\SecurityCodeScan\config-2.0.yml

SCS logs:
AD0001	Analyzer 'SecurityCodeScan.Analyzers.CSharpAnalyzers' threw an exception of type 'YamlDotNet.Core.YamlException' with message '(Line: 4, Col: 1, Idx: 108) - (Line: 4, Col: 1, Idx: 108): Exception during deserialization'.	

Using SecurityCodeScan.VS2017 3.2.0

I have tried some different settings
Adding Version: 2.0 to the yml file.
Remove everything but AuditMode: true.
Use the file as is without any modifications. 
Adding the file directly to the project instead of de global location. 

But they all lead to the same exception. 
Does anyone have a suggestion to make this work?

**Comment by JarLob** [comment]
There is a line number in the exception. I don't think it is the same in all cases you tried.
https://github.com/security-code-scan/security-code-scan/blob/master/SecurityCodeScan/Config/Main.yml format has changed recently. It is compatible only with a custom build from sources and will not work with the extension from marketplace (not released yet).
Btw you don't need to copy whole Main.yml, it is overkill.
However if you used something simple as
```yml
AuditMode: true
```
in `config-2.0.yml` it had to work in all cases.
I suggest you adding exact yml file you used and exact error you got and a comment if it was installed from marketplace or built. Otherwise it is just guessing.

**Comment by CodeGlitcher** [comment]
Hi JarLob,

I tried AuditMode: true only and it does work.
Maybe the last time visual studio had the old file cached.

Thanks for your help
