### ISSUE TITLE
XMLSerizializer constructor with parameters give scs0028 

### ISSUE THREAD

**Issue by danleydmello** [security-code-scan/security-code-scan#158]
In my code I want to serialize the class using XmlSerializerc(GetType()) constructor. But Security scanner raise scs0028 . I thought this rule was only for deserialization.

**Comment by JarLob** [comment]
Sorry for the delay.

Yes, you are right, the warning is valid for **deserialization** only.  However since `XmlSerializer` is vulnerable only if the attacker controls the type it was easier to write two sinks in this case: for the constructor and the `Deserialize` method. Otherwise a separate analyzer should be written for `XmlSerializer`, something similar to the existing XXE analyzer.

All in all, the issue is valid. I'll keep it as a reminder. Contributions are welcome.

**Comment by JarLob** [comment]
Merging with #68
