### ISSUE TITLE
Scan does not detect vulnerabilities

### ISSUE THREAD

**Issue by benfoster** [security-code-scan/security-code-scan#183]
**Environment (please complete the following information):** 
 - Version [e.g. 3.3.0] Latest stable for both versions
 - Branch [SCS or SCS2017] Both
 - Visual Studio [e.g. 2019 (16.3.6)] VS Code
 - OS: [e.g. Windows, Linux] macOS Catalina 10.16.6

**Describe the bug**

I have installed both the SecurityCodeScan (warning that it has been deprecated) and *.VS2019 packages and neither of them raises any warnings in VS Code for the code below (I have analyzers enabled in Omnisharp).

I have also tried installing the global tool and do not get any warnings.

**Repro**

Sample code:

```c#
       public static void DoTheNaughty(string input)
        {
            var p = new Process();
            p.StartInfo.FileName = "exportLegacy.exe";
            p.StartInfo.Arguments = " -user " + input + " -role user";
            p.Start();

            var doc = new XmlDocument {XmlResolver = null};
            doc.Load("/config.xml");
            _ = doc.SelectNodes("/Config/Devices/Device[id='" + input + "']");
        }
```

Running the global tool:

```
dotnet security-scan ./Guard.sln
```

Have I misunderstood how to use this tool?

**Comment by JarLob** [comment]
> **Environment (please complete the following information):** 
> - Version [e.g. 3.3.0] Latest stable for both versions
> - Branch [SCS or SCS2017] Both
> - Visual Studio [e.g. 2019 (16.3.6)] VS Code
> - OS: [e.g. Windows, Linux] macOS Catalina 10.16.6

The information is very confusing since later you say you run the global tool.
The only supported version is v5.0.0 from vs2019 branch.
There is no extension for Visual Studio Code, but global tool can run everywhere.

Said that, is the `input` tainted? SCS gives a warning when the input is untrusted. You may look at the unit tests that typically use input from web controllers.
Another option is to add new taint source into a user configuration:
https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan/Config/Main.yml#L22
https://github.com/security-code-scan/security-code-scan/blob/vs2019/SecurityCodeScan/Config/Main.yml#L91

**Comment by benfoster** [comment]
I've tried the standalone packages and the global tool. I think the taint source is the detail I was missing. I will review the examples.
