### ISSUE TITLE
Update YamlDotNet

### ISSUE THREAD

**Issue by AraHaan** [security-code-scan/security-code-scan#208]
Environment: 
 - Version: 5.1.0 (or latest version published to nuget.org as resolved by the ``*-*`` version pattern and yes I always wildcard these due to AI issues and much too frequent changes to packages that cause more issues maintaining than just wildcarding them)
 - Branch:
   - [x] vs2019 
   - [ ] vs2017 
   - [ ] vs2015 
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [x] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [x] Windows
   - [x] Linux
   - [x] Mac

**Describe the bug**
The issue with this is this Analyzer uses an outdated version of YamlDotNet, which conflicts with those used by other analyzers / SourceGenerators like CsWin32.

**Repro**
The repro is as simple as visiting https://github.com/microsoft/CsWin32/issues/221 and cloning the repository in the comments (and the related branch) then running said analyzer in debug to expose another roslyn issue (it does not self contain each loaded analyzer / sourcegenerator which I think it should be done to their own AssemblyLoadContext). However because of that bug we run into this bug where the Analyzer loads the *older* version of that package first, then the source generator tries to load version 11.x.x of the same dependency resulting in noticeable build failures in the pull request made from that branch.

Possible Solutions:
- Wildcard the dependency versions so then they work.
- wait till a fix to roslyn is made (could possibly take a long while to fix that one).
- have CIs automatically update all of the dependencies automatically then frequently have it push new preview releases with said updates (that pass and get merged) to nuget.org automatically.

I think Option 1, or 3 is the best in this case for quick fixes with 2 being meh later on.

**Comment by JarLob** [comment]
Thanks for pointing to the issue. I thought a similar [problem](https://github.com/security-code-scan/security-code-scan/issues/164) was already fixed in https://github.com/security-code-scan/security-code-scan/commit/bfd7677a2e914e623d752a89422223b4d92a092f. Looking now at the commit message I wonder why I wrote "signed" because I didn't actually referenced now deprecated [signed YamlDotNet](https://www.nuget.org/packages/YamlDotNet.Signed/), but just bumped it to 8.1.1. It can be I meant "strong typed" as described in https://github.com/aaubry/YamlDotNet/issues/372#issuecomment-479194566 `From release 6.0.0, the YamlDotNet assembly will always have a strong name`. This supposedly had to fix side loading of the different versions.

By [Option 1](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning), do you mean `<PackageReference Include="YamlDotNet" Version="*" />`? I don't think this changes anything since SCS delivers a copy of YamlDotNet.dll by itself. While I can and will update SCS to the latest stable YamlDotNet version in the next release it just changes who will load an older version of YamlDotNet. The classic dll hell issue. You can't expect everyone to use the same bleeding edge version of the library. BTW major versions of YamlDotNet may be incompatible by design according to the author: `if you upgrade a major version, you should expect to have to make changes to your code anyways`.

**Comment by AraHaan** [comment]
By Option one I mean ``<PackageReference Include="YamlDotNet" Version="*-*" />`` (which is to consume the latest stable / prerelease version depending on which one is deemed newer according to what nuget thinks is newest).

Wait SCS uses that dependency too?, cant that dependency indirectly by used then without needing to reference that package in the analyzer directly then?

**Comment by JarLob** [comment]
> Wait SCS uses that dependency too?, cant that dependency indirectly by used then without needing to reference that package in the analyzer directly then?

YamlDotNet is used to deserialize SCS configuration file.
The analyzer cannot just assume the library is referenced by the analyzed project, because it may not need it. By "indirectly" do you mean `Assembly.Load`? Since major YamlDotNet versions may have breaking changes, it may load an incompatible version.

**Comment by AraHaan** [comment]
> > Wait SCS uses that dependency too?, cant that dependency indirectly by used then without needing to reference that package in the analyzer directly then?
> 
> YamlDotNet is used to deserialize SCS configuration file.
> The analyzer cannot just assume the library is referenced by the analyzed project, because it may not need it. By "indirectly" do you mean `Assembly.Load`? Since major YamlDotNet versions may have breaking changes, it may load an incompatible version.

indirectly as in when the ``Microsoft.CodeAnalysis.*`` packages load it (if it ever does) itself.

I guess another way to resolve this is to somehow do an binding redirect between v8 of YamlDotNet and v11 or w/e latest version is of YamlDotNet but not entirely sure if that could work too.
