### ISSUE TITLE
Running security-code-scan on linux

### ISSUE THREAD

**Issue by juli1** [security-code-scan/security-code-scan#226]
**Environment:**
 - Installation/Running method:
   - [x] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [ ] Windows
   - [x] Linux
   - [ ] Mac

**Describe the bug**

Once getting the package from `nuget` on Linux, there is no way to execute it. Maybe this is because I am not totally familiar with the `nuget` and package management ecosystem.

When using `nuget install security-scan`, a new directory `security-scan-5.2.2` is created but there are no binary (not even a `.exe` file).

How can I then use the tool on Linux?

**Comment by JarLob** [comment]
I tried installing the `security-scan` [dotnet tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) on Ubuntu VM and Ubuntu WSL (Windows Subsystem for Linux) with the following results:
VM
```
azureuser@ubuntu:~$ dotnet tool install --global security-scan
You can invoke the tool using the following command: security-scan
Tool 'security-scan' (version '5.2.2') was successfully installed.
azureuser@ubuntu:~$ security-scan

.....................
.NET tool by Jaroslav Lobačevski v5.2.2.0
```
WSL
```
user@Notebook:~$ dotnet tool install --global security-scan
Since you just installed the .NET SDK, you will need to logout or restart your session before running the tool you installed.
You can invoke the tool using the following command: security-scan
Tool 'security-scan' (version '5.2.2') was successfully installed.
user@Notebook:~$ security-scan
security-scan: command not found
```
In both cases it creates a binary file `$HOME/.dotnet/tools/security-scan`.
The [documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) states that `This location is added to the user's path when the SDK is first run, so global tools can be invoked from any directory without specifying the tool location.` and you also see `Since you just installed the .NET SDK, you will need to logout or restart your session before running the tool you installed.` in the post install message, so `$HOME/.dotnet/tools` was not in my path on Ubuntu WSL, but I was still able to run `$HOME/.dotnet/tools/security-scan` directly (binaries on Linux do not need to have an extension).

**Comment by juli1** [comment]
Hi @JarLob,

Thank you so much for the details, I really appreciate it. I was using `nuget` on debian and obviously, the right thing to do is to use `dotnet`. It worked perfectly on Debian 10.

Thanks for the help,
