### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by catherinelpowell** [security-code-scan/security-code-scan#243]
Hi. I'm trying to use SCS and running into 2 separate issues.  Can you please help?  

OS: Windows 10
ASP.NET OWASP WebGoat (.NET 3.5) and .NET 4.8 webforms projects
SCS 5.6.2

1. Regarding the standalone tool...
I installed the security-scan4x from GitHub Releases on 2 different machines:

 a. On a machine with VS 2022 installed => The security scan tool was installed successfully.  However, running it against WebGoat produced the following error:

 Msbuild failed when processing the file '...\OWASP-WebGoat.NET-e9603b9\WebGoat\WebGoat.NET.csproj' with message: The imported project "C:\Program Files\dotnet\sdk\6.0.201\Microsoft\VisualStudio\v17.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\6.0.201\Microsoft\VisualStudio\v17.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.

 b. On a machine with VS 2017 installed I received the following error when I tried to install SCS:

   error NU1202: Package security-scan 5.6.2 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any. Package security-scan 5.6.2 supports:
    error NU1202:   - net50 (.NETFramework,Version=v5.0) / any
    error NU1202:   - net60 (.NETFramework,Version=v6.0) / any
    The tool package could not be restored.
    Tool 'security-scan' failed to install. This failure may have been caused by:
    
   * You are attempting to install a preview release and did not use the --version option to specify the version.
   * A package by this name was found, but it was not a .NET Core tool.
   * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
   * You mistyped the name of the tool.

2. I tried the VS extension as well and, after updating the .vbproj file with the AdditionalFileItemNames element, this worked well with our webapplication projects.  However, we also have a lot of website projects that do not contain project files.  Is there something I can set so that the scanner picks up issues in the web.config and .aspx files of websites?

Thank you very kindly in advance.

**Comment by JarLob** [comment]
Hi Catherine,

>I installed the security-scan4x from GitHub Releases
>On a machine with VS 2017 installed I received the following error when I tried to install SCS

How do you install it? The stand-alone [security-scan4x.zip](https://github.com/security-code-scan/security-code-scan/releases/download/5.6.2/security-scan4x.zip) is a zip with a classic dotnet exe, that just needs to be extracted. Then just run the exe with parameters.

The stand-alone dotnet tool [security-scan.5.6.2.nupkg](https://github.com/security-code-scan/security-code-scan/releases/download/5.6.2/security-scan.5.6.2.nupkg) is there just for reference. Although you may download and install it to with `dotnet tool install` with the `--add-source` flag, it is not needed, you may install directly from nuget with `dotnet tool install --global security-scan --version 5.6.2`. You can invoke it as `security-scan` without specifying a path after installation.

>However, we also have a lot of website projects that do not contain project files.

The stand-alone tool requires project/solution for analysis. It doesn't work with single code files. VS extension may work when a code file is open instead of project file (depends on VS internals, how it handles, compiles and analyses such project-less files), but the best results you will get when a project/solution is opened.
