### ISSUE TITLE
Issues when using on bitbucket pipeline

### ISSUE THREAD

**Issue by elfico** [security-code-scan/security-code-scan#246]
**Environment:**
 - Version: 5.6.2
 - 
 - Installation/Running method:
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
 - Operating System:
   - [ ] Linux

**Describe the bug**
Trying to add this to build pipelines and I am getting this error:
dotnet tool install --global security-scan
error NU1202: Package security-scan 5.6.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package security-scan 5.6.2 supports:
error NU1202:   - net5.0 (.NETCoreApp,Version=v5.0) / any
error NU1202:   - net6.0 (.NETCoreApp,Version=v6.0) / any
The tool package could not be restored.
Tool 'security-scan' failed to install. This failure may have been caused by:
* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by JarLob** [comment]
Thank you for bringing it up.
Since you are installing it globally I guess you have multiple options:
1. Install .net 5
2. If you have full dotnet framework installed - download, extract and use https://github.com/security-code-scan/security-code-scan/releases/download/5.6.2/security-scan4x.zip
3. Install the older version of the dotnet tool security-scan
