### ISSUE TITLE
Standalone can not understand shproj.

### ISSUE THREAD

**Issue by Cestbienmoi** [security-code-scan/security-code-scan#253]
**Environment:**
 - Version: 5.6.3
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [ ] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - [x] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [x] Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
If we use shared project (shproj) in sln the tool show error (for each shproj) :
Cannot open project 'xxx\WebPHv3.Shared.shproj' because the file extension '.shproj' is not associated with a language.

**Repro**
part of sln:
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WebPHv3.JS", "WebPHv3.JS\WebPHv3.JS.csproj", "{3A3063BA-BC2E-4A91-B893-5713D1D16BC6}"
EndProject
Project("{D954291E-2A0B-460D-934E-DC6B0785DB48}") = "WebPHv3.Shared", "WebPHv3.Shared\WebPHv3.Shared.shproj", "{9AE4BAE3-5B40-4893-8315-D4FB3EE83DF4}"
EndProject

**workaround**
--ignore-msbuild-errors

**Comment by JarLob** [comment]
Thank you for reporting this. As you already noticed the workaround is to use `--ignore-msbuild-errors`. Also seems there is an old issue in Roslyn for this - https://github.com/dotnet/roslyn/issues/29696
However since it is not the first time (see https://github.com/security-code-scan/security-code-scan/issues/235 and https://github.com/security-code-scan/security-code-scan/issues/201#issuecomment-876307629) I have decided to fix it with some disadvantages using reflection - https://github.com/security-code-scan/security-code-scan/commit/27ea8adeb4e7b6a9b807704c455ff67f376fe960

**Comment by JarLob** [comment]
FYI, it was implemented in 5.6.4
