### ISSUE TITLE
Session Terminated unexpectedly. Disabling 'Security Code Scan 2.8.0' might help prevent similar issues

### ISSUE THREAD

**Issue by DocGitHub** [security-code-scan/security-code-scan#89]
Session Terminated unexpectedly. Disabling 'Security Code Scan 2.8.0' might help prevent similar issues

I attached my ActivityLog. It happens, while running the application inside Visual Studio. 
It happened multiple times and when the addon is disabled i can debug this program version / branch again.

[ActivityLog.zip](https://github.com/security-code-scan/security-code-scan/files/2553449/ActivityLog.zip)

**Comment by JarLob** [comment]
1. It is open source you can build it and start debugging. It will open another visual studio in which you open the problematic solution.
2. Another option is to use Nuget package instead of studio extension. Should run the analysis only on build instead of background.
3. Or try disabling whole solution analysis. You may miss some issues, but should run faster.
4. There are remains of logging in the sources, but I haven't tried it my self.

**Comment by JarLob** [comment]
Should be fixed by dbd7acff9fbcc0bbde3caf2c01b21ee9ff482242
